### ISSUE TITLE
Simplified Chinese Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-zh-Hans#1]
## 致新的翻译者

翻译页面的流程：

1. 检查下面的清单和评论，保证要翻译的页面没有与他人冲突。
2. 在评论中回复你想翻译页面的名称。 **请一次申请一个页面**。
3. Clone 这个仓库，翻译你的页面，提交 PR！

在开始贡献你的力量之前，请先阅读[翻译指南](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation)以便理解 Gatsby 文档的翻译流程。

对自己的翻译负责！当你无法再提交翻译时，请及时通知 maintainers ，以便他们能将这些页面分配给其他人。

## 致 Maintainers

如果某个自愿者翻译了某个页面，请以如下格式更新这个 issue：

- [ ] Home Page (@gatsbybot) #1

当 PR 合并后，确保标记该页面为已完成状态。

## 核心页面

**这些页面应该被优先翻译。** 这些页面都翻译完成后，才能视为这是一个官方的简体中文文档。

### Community 

* [x] community/code-of-conduct (@nelsonkuang ) #3 
    

### Tutorial

* [x] tutorial/index (@nelsonkuang) #3
* [x] tutorial/part-zero (@nelsonkuang) #6
* [x] tutorial/part-one (@Pike96) #8
* [x] tutorial/part-two (@nelsonkuang) #6
* [x] tutorial/part-three (@nelsonkuang) #7
* [x] tutorial/part-four (@Pike96) #10
* [x] tutorial/part-five (@Pike96) #13
* [x] tutorial/part-six (@Pike96) #14
* [x] tutorial/part-seven (@Pike96) #16
* [x] tutorial/part-eight (@Pike96) #17

### Docs

* [x] docs/index (@mayneyao ) #18 
* [x] docs/quick-start (@mayneyao ) #18 
* [x] docs/recipes (@Pike96) #25
* [x] docs/glossary (@Pike96) #26
* [x] docs/gatsby-cli (@mayneyao ) #18 

## 优先级较高的页面

根据[翻译指南](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation)中提到的[页面优先级表格](https://docs.google.com/spreadsheets/d/1u2amGnqFLKxJuL5h9UrDblUueFgg0EBt7xbau4n8iTM/edit)，除了上面提到的核心页面外，下面这些页面也应该被优先翻译。在有余力的情况下，翻译者可优先翻译下面这些页面：

### Docs

* [x] docs/gatsby-link (@Pike96) #27 
* [ ] docs/node-apis
* [x] docs/themes/what-are-gatsby-themes (@mayneyao ) #12 
* [x] docs/guides (@lgnov ) #21 
* [x] docs/themes (@lgnov ) #20 
* [x] docs/graphql-concepts (@lgnov ) #24 
* [x] docs/importing-assets-into-files (@lgnov ) #23 
* [x] docs/headless-cms (@lgnov ) #19 
* [x] docs/deploying-and-hosting (@lgnov ) #22 
* [x] docs/working-with-images (@lgnov ) #28 
* [ ] docs/creating-and-modifying-pages (@evading1998)
* [ ] docs/environment-variables

### Tutorial

* [x] tutorial/theme-tutorials（@mayneyao）#9
* [x] tutorial/using-a-theme（@mayneyao）#9
* [x] tutorial/using-multiple-themes-together（@mayneyao) #15 

### Docs

* [x] docs/themes/theme-composition (@mayneyao ) #15 
* [x] docs/themes/using-multiple-gatsby-themes (@mayneyao ) #15

**Comment by Pike96** [comment]
Can I take `tutorial/part-one`?

**Comment by nelsonkuang** [comment]
> Can I take `tutorial/part-one`?

just do it

**Comment by Pike96** [comment]
`tutorial/part-four`?
(To maintainer: Just add reaction. No need to reply in comment. Personally I don't like the issue being too long 😂)

**Comment by mayneyao** [comment]
`docs/tutorial/theme-tutorials.md`

**Comment by mayneyao** [comment]
`docs/themes/what-are-gatsby-themes.md`

**Comment by Pike96** [comment]
You can do this for avoiding making a pull request.

1. `git remote add upstream https://github.com/gatsbyjs/gatsby-zh-Hans.git`
2. Fetch it and merge gatsbyjs's `master` to your forked repo's `master`.

So your pull request won't appear here like above `Merge pull request #1 from gatsbyjs/master` ☝️

**Comment by lgnov** [comment]
`docs/headless-cms.md`

**Comment by lgnov** [comment]
`docs/themes.md`

**Comment by lgnov** [comment]
`docs/guides.md`

**Comment by lgnov** [comment]
`docs/graphql-concepts.md`
`docs/importing-assets-into-files`
`docs/deploying-and-hosting`

**Comment by evading1998** [comment]
docs/creating-and-modifying-pages.md

**Comment by xgqfrms** [comment]
# where are the translated docs?

> Could you give a URL link, please.


https://www.gatsbyjs.com/docs/zh-CN/tutorial/

https://www.gatsbyjs.com/docs/zh-Hans/tutorial/

![image](https://user-images.githubusercontent.com/7291672/104535901-fa808b00-5651-11eb-8833-4eb61ae74516.png)
